server:
  port: 8040

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
logging:
  level:
    com.tulingxuyan.order.feign: debug